### ISSUE TITLE
Criação do github pages.

### ISSUE THREAD

**Issue by JoaoHenrique12** [Interacao-Humano-Computador/2020.2-forumPiR2#1]
A criação do nosso github pages para expor a introdução de nosso trabalho é fundamental para transmitir bem nossas ideias. Portanto criem um pages com uma boa estrutura que pode ser facilmente expandida.

- [x] Criação do pages com a estrutura inicial do projeto

**Comment by ailtonaires** [comment]
Criação do escopo inicial do GitHub Pages finalizada.
