### ISSUE TITLE
Análise Hierárquica de Tarefas

### ISSUE THREAD

**Issue by JoaoHenrique12** [Interacao-Humano-Computador/2020.2-forumPiR2#2]
O objetivo desta issue e criar os/as diagramas/tabelas que representem as principais tarefas e seus objetivos do Forum Pir2, portanto para a resolucao deste problema o PR deve conter:

- [x] Identificacao dos objetivos de alto nivel do forum
- [x] Um ou mais arquivos MD contendo os diagramas ou tabelas que representem cada tarefa a ser desempenhada para alcancar os objetivos no forum

**Comment by liversonp** [comment]
Issue concluída com sucesso.

link do pull request: https://github.com/Interacao-Humano-Computador/2020.2-forumPiR2/pull/7
