### ISSUE TITLE
Perfil do usuário

### ISSUE THREAD

**Issue by JoaoHenrique12** [Interacao-Humano-Computador/2020.2-forumPiR2#3]
Esta issue baseia-se em resolver o problema de identificacao dos usuarios do forum Pir2, portanto temos os seguintes objetivos:

- [x] Definir o metodo de coleta de dados dos usuarios
- [x] Quais dados serao coletados
- [x] Como expor tais dados de uma maneira de facil compreencao para humanos

**Comment by Denniel-sudo** [comment]
https://github.com/Interacao-Humano-Computador/2020.2-forumPiR2/pull/5
