### ISSUE TITLE
Principios gerais e Metas de usabilidade.

### ISSUE THREAD

**Issue by JoaoHenrique12** [Interacao-Humano-Computador/2020.2-forumPiR2#9]
Os objetivos principais desta atividade baseiam-se em:
- [x] Documentar quais metas de usabilidade o site nao cumpre e seus impactos sobre a realizacao das atividades.
- [x] Explicitar os principios gerais do projeto, embasado em referencial bibliografico.
- [x] Busque explicar tambem quais sao as principais metas de usabilidade para o contexto de IHC.

**Comment by victordsantoss** [comment]
Documentos implementados + alterações no documento de personas.
